### PR TITLE
Updated gemspec and changelog + remove 1.9 support leftovers

### PR DESCRIPTION
**Pull request by ivoanjo**
See individual commit messages for more details.

Thanks for working on this tiny gem! I make use of in in my own [backtracie](https://github.com/ivoanjo/backtracie) and it's been a great way to get access to things I shouldn't mess with ;)

### CODE REVIEW

**Comment by ivoanjo** [comment]
Hey @hurricup just a tiny ping in case you've missed this PR :)
Let me know if I can help in any other way ^^

**Comment by hurricup** [comment]
Sorry, had no time to check this yet.

**Comment by ivoanjo** [comment]
Cool cool cool, no hurries!

**Comment by ivoanjo** [comment]
Just saw there was a new release, would be nice to get this PR in as well!

**Comment by ivoanjo** [comment]
😭

**Comment by hurricup** [comment]
Thank you.

**Comment by ivoanjo** [comment]
Awesome, thanks for adding this in! :)

**Pull request merged**
